rule all:
   input:
      directory("results/multiqc")

rule fastqc:
   input:
      expand("../data/{sample}.fastq", sample=SAMPLES)
   output:
      directory("results/fastqc")
   log:
      "logs/fastqc.log"
   threads: 10
   resources:
      runtime: 10 #in minutes
      mem_mb: 1500 #in mb
   shell:
      bash scripts/fastqc.sh {input} {output} {log} {threads}

rule multiqc:
   input:
      directory("results/fastqc")
   output:
      directory("results/multiqc")
   params:
      multiqc_env="config/multiqc.yml"
   log:
      "logs/multiqc.log"
   threads: 1
   resources:
      runtime: 10
      mem_mb: 300
   conda:
      "config/multiqc.yml"
   shell:
      bash scripts/multiqc.sh {input} {output} {params.multiqc_env} {log}