SAMPLES = ["F1_1_WGS_MGI_L001_R1", "F1_1_WGS_MGI_L001_R2"]

rule all:
   input:
      "results/multiqc"

rule fastqc:
   input:
      expand("../data/{sample}.fastq",sample=SAMPLES)
   output:
      directory("results/fastqc")
   log:
      "logs/fastqc.log"
   threads: 10
   resources:
      runtime=10, #in minutes
      mem_mb=1500 #in mb
   shell:
      """
      ml fastqc/0.12.1

      #runs the fastqc
      # -o takes output directory, --extract unzips output reports, --delete removes zipped reports after, file taken as an argument
      fastqc \
         -o {output} \
         --extract \
         --delete \
         --threads {threads} \
         {input} &>> {log}
      """

rule multiqc:
   input:
      "results/fastqc"
   output:
      directory("results/multiqc")
   params:
      multiqc_env="config/multiqc.yml"
   log:
      "logs/multiqc.log"
   threads: 1
   resources:
      runtime=10,
      mem_mb=300
   conda:
      "config/multiqc.yml"
   shell:
      "bash scripts/multiqc.sh {input} {output} {params.multiqc_env} {log}"
