"""
Phasing using the HPRC haplotype VCF as a reference panel. This is a smaller version of the
panel, but it's guaranteed to contain the variants I genotyped from.

Because of the small sample size I decided to omit phase_rare, and I think I can get away
with phase_common on the entire chromosome. Even though this is WGS and not GWAS/array,
there are so few samples I'm willing to gamble here.

Pipeline:
  index sample VCFs
  merge samples into one BCF
  split merged VCF into chrs
  phase each chr of the merged VCF by SHAPEIT common phasing
  concat phased chromosomes into the final BCF
"""

SAMPLES = ["F1", "M1", "F2"]
CHRS = [f"{i}" for i in range(1, 23)]

SHAPEIT_BIN = "~/bin/shapeit/phase_common/bin" # the phase_common binary directory (need to build for each tool)
PANGENIE_DIR = "/scratch/atran/final/3_pangenie/vcfs" #directory of Pangenie genotyping results
RAW_PANEL = "/scratch/atran/final/3_pangenie" #HPRC VCF

rule all:
   input:
      "results/phased_complete.bcf"

rule index_vcfs:
   input:
      f"{PANGENIE_DIR}/{{sample}}_genotyping_biallelic.vcf" #phase the full genotypes, not just the alts, present in biallelic form
   output:
      gz  = "results/index_vcfs/{sample}.vcf.gz",
      csi = "results/index_vcfs/{sample}.vcf.gz.csi"
   log:
      "logs/index_vcfs_{sample}.log"
   threads: 4
   resources:
      runtime = 15,
      mem_mb  = 500
   shell:
      # -k and -f respectively keeps the raw file when zipped and forces rewrites if file is present
      # I move the bgzipped file to the new directory so we can work with it.
      # then bcftools indexing happens in the output folder
      """
      ml samtools/1.18
      ml bcftools/1.18
      bgzip -k -f --threads {threads} {input} 2> {log}
      mv {input}.gz {output.gz}
      bcftools index -f --threads {threads} {output.gz} 2>> {log}
      """

rule combine_vcfs:
   input:
      gz  = expand("results/index_vcfs/{sample}.vcf.gz", sample=SAMPLES),
      csi = expand("results/index_vcfs/{sample}.vcf.gz.csi", sample=SAMPLES)
   output:
      bcf = "results/combine_vcfs/combined.bcf",
      csi = "results/combine_vcfs/combined.bcf.csi"
   log:
      "logs/combine_vcfs.log"
   threads: 4
   resources:
      runtime = 15,
      mem_mb  = 500
   shell:
      # -m none keeps records biallelic (no multiallelic merging)
      # -W writes index alongside output
      # -Ob forces writing as a compressed bcf, which allows for the index to be written
      """
      ml samtools/1.18
      ml bcftools/1.18
      bcftools merge \
         --threads {threads} \
         -m none \
         -W \
         -Ob \
         -o {output.bcf} {input.gz} 2> {log}
      """

rule split_target_by_chr:
   input:
      bcf = "results/combine_vcfs/combined.bcf",
      csi = "results/combine_vcfs/combined.bcf.csi"
   output:
      bcf = "results/split_target/combined_chr{chr}.bcf",
      csi = "results/split_target/combined_chr{chr}.bcf.csi"
   log:
      "logs/split_target_chr{chr}.log"
   threads: 4
   resources:
      runtime = 60,
      mem_mb  = 500
   shell:
      """
      ml samtools/1.18
      ml bcftools/1.18
      bcftools view \
         --threads {threads} \
         -r {wildcards.chr} \
         -Ob -o {output.bcf} {input.bcf} 2> {log}
      bcftools index -f --threads {threads} {output.bcf} 2>> {log}
      """

rule split_panel_by_chr:
   input:
      panel = RAW_PANEL
   output:
      bcf = "results/split_panel/panel_chr{chr}.bcf",
      csi = "results/split_panel/panel_chr{chr}.bcf.csi"
   log:
      "logs/split_panel_chr{chr}.log"
   threads: 4
   resources:
      runtime = 60,
      mem_mb  = 1000
   shell:
      #view each chromosome in compressed bcf format and write an index with -W
      """
      ml samtools/1.18
      ml bcftools/1.18
      bcftools view --threads {threads} \
         -r {wildcards.chr} \
         -W csi \
         -Ob -o {output.bcf} {input.panel} 2> {log}
      """

rule phase_common:
   input:
      genotype = "results/split_target/combined_chr{chr}.bcf",
      gt_csi   = "results/split_target/combined_chr{chr}.bcf.csi",
      panel    = "results/split_panel/panel_chr{chr}.bcf",
      panel_csi= "results/split_panel/panel_chr{chr}.bcf.csi",
      map_file = "inputs/maps/chr{chr}.gmap.gz",
      pedigree = "config/family.fam"
   output:
      bcf = "results/phase_common/phased_{chr}.bcf",
      csi = "results/phase_common/phased_{chr}.bcf.csi"
   log:
      "logs/phase_common_chr{chr}.log"
   threads: 12
   resources:
      runtime = 120,
      mem_mb  = 1200
   shell:
      # whole chr phasing, to avoid ligation
      # --filter-maf omitted so rare variants / MEIs are retained
      # --pedigree for the family relationship/duo phasing
      """
      {SHAPEIT_BIN}/phase_common \
         --input {input.genotype} \
         --reference {input.panel} \
         --map {input.map_file} \
         --pedigree {input.pedigree} \
         --region {wildcards.chr} \
         --output {output.bcf} \
         --log {log} \
         --thread {threads}
      ml samtools/1.18
      ml bcftools/
      bcftools index -f --threads {threads} {output.bcf}
      """

rule concat_chrs:
   input:
      bcf = expand("results/phase_common/phased_{chr}.bcf", chr=CHRS),
      csi = expand("results/phase_common/phased_{chr}.bcf.csi", chr=CHRS)
   output:
      "results/phased_complete.bcf"
   log:
      "logs/concat_chrs.log"
   threads: 1
   resources:
      runtime = 10,
      mem_mb  = 100
   shell:
      # -n : fast concat without recompression (inputs already sorted, non-overlapping by chr)
      """
      ml samtools/1.18
      ml bcftools/1.18

      mkdir tmp
      echo "{input.bcf}" | sed 's/ /\n/g' | sort -t "_" -k3,3n > tmp/input_bcf.txt

      bcftools concat \
         --naive \
         -f tmp/input_bcf.txt \
         --threads {threads} \
         -W \
         -Ob -o {output} {input.bcf} 2> {log}
      """
